import type { CatalogDef } from '~/types/catalogs'

// Declarative registry of the manageable catalogs. A single dynamic page
// (pages/dashboard/catalogs/[resource].vue) is built from these definitions,
// avoiding one page per entity.
//
// Patterns/maxes taken from the OpenAPI (/v3/api-docs). `code`/`isoCode` and the FKs
// (countryUuid, stateUuid) are immutable: set only on create (onlyCreate).
//
// `label`/`labelSingular`/field labels/`regexMsg` are the Spanish fallback; the
// `*Key` variants are resolved to i18n where consumed (the [resource] page and the nav).

const CODE_40 = /^[A-Z_]{1,40}$/
const codeMsg = (n: number) => `Mayúsculas/guion bajo, máx. ${n}`

export const CATALOGS: CatalogDef[] = [
  {
    key: 'countries',
    basePath: '/v1/admin/catalogs/countries',
    viewPermission: 'COUNTRY_VIEW_ALL',
    createPermission: 'COUNTRY_CREATE',
    updatePermission: 'COUNTRY_UPDATE',
    deletePermission: 'COUNTRY_DELETE',
    label: 'Países',
    labelSingular: 'País',
    labelKey: 'catalogs.registry.countries.label',
    labelSingularKey: 'catalogs.registry.countries.labelSingular',
    icon: 'i-lucide-globe',
    codeField: 'isoCode',
    auditEntityKey: 'country',
    auditPermission: 'COUNTRY_RECORD_AUDIT_VIEW',
    auditReportPermission: 'COUNTRY_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'isoCode', label: 'Código ISO', labelKey: 'catalogs.fields.isoCode', type: 'text', required: true, onlyCreate: true, regex: /^[A-Z]{2}$/, regexMsg: 'Dos letras mayúsculas (ISO 3166-1, p.ej. VE)', regexMsgKey: 'catalogs.validation.isoCode', max: 2, placeholder: 'VE' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
    ],
  },
  {
    key: 'states',
    basePath: '/v1/admin/catalogs/states',
    viewPermission: 'STATE_VIEW_ALL',
    createPermission: 'STATE_CREATE',
    updatePermission: 'STATE_UPDATE',
    deletePermission: 'STATE_DELETE',
    label: 'Estados / Departamentos',
    labelSingular: 'Estado',
    labelKey: 'catalogs.registry.states.label',
    labelSingularKey: 'catalogs.registry.states.labelSingular',
    icon: 'i-lucide-map',
    codeField: 'code',
    parentDisplayField: 'country_Code',
    parentDisplayLabelField: 'country_Display',
    auditEntityKey: 'state',
    auditPermission: 'STATE_RECORD_AUDIT_VIEW',
    auditReportPermission: 'STATE_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'countryUuid', label: 'País', labelKey: 'catalogs.fields.country', type: 'parent', required: true, onlyCreate: true, parentKey: 'countries' },
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, max: 10, placeholder: 'MIR' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
    ],
  },
  {
    key: 'cities',
    basePath: '/v1/admin/catalogs/cities',
    viewPermission: 'CITY_VIEW_ALL',
    createPermission: 'CITY_CREATE',
    updatePermission: 'CITY_UPDATE',
    deletePermission: 'CITY_DELETE',
    label: 'Ciudades',
    labelSingular: 'Ciudad',
    labelKey: 'catalogs.registry.cities.label',
    labelSingularKey: 'catalogs.registry.cities.labelSingular',
    icon: 'i-lucide-building-2',
    parentDisplayField: 'state_Code',
    parentDisplayLabelField: 'state_Display',
    listFilter: { param: 'stateUuid', field: 'stateUuid' },
    auditEntityKey: 'city',
    auditPermission: 'CITY_RECORD_AUDIT_VIEW',
    auditReportPermission: 'CITY_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'stateUuid', label: 'Estado / Departamento', labelKey: 'catalogs.fields.state', type: 'parent', required: true, onlyCreate: true, parentKey: 'states' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 120 },
    ],
  },
  {
    key: 'genders',
    basePath: '/v1/admin/catalogs/genders',
    viewPermission: 'GENDER_VIEW_ALL',
    createPermission: 'GENDER_CREATE',
    updatePermission: 'GENDER_UPDATE',
    deletePermission: 'GENDER_DELETE',
    label: 'Géneros',
    labelSingular: 'Género',
    labelKey: 'catalogs.registry.genders.label',
    labelSingularKey: 'catalogs.registry.genders.labelSingular',
    icon: 'i-lucide-venus-and-mars',
    codeField: 'code',
    auditEntityKey: 'gender',
    auditPermission: 'GENDER_RECORD_AUDIT_VIEW',
    auditReportPermission: 'GENDER_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: /^[A-Z]$/, regexMsg: 'Una letra mayúscula (p.ej. M, F)', regexMsgKey: 'catalogs.validation.genderCode', max: 1, placeholder: 'M' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 20 },
    ],
  },
  {
    key: 'document-types',
    basePath: '/v1/admin/catalogs/document-types',
    viewPermission: 'DOCUMENT_TYPE_VIEW_ALL',
    createPermission: 'DOCUMENT_TYPE_CREATE',
    updatePermission: 'DOCUMENT_TYPE_UPDATE',
    deletePermission: 'DOCUMENT_TYPE_DELETE',
    label: 'Tipos de documento',
    labelSingular: 'Tipo de documento',
    labelKey: 'catalogs.registry.document-types.label',
    labelSingularKey: 'catalogs.registry.document-types.labelSingular',
    icon: 'i-lucide-id-card',
    codeField: 'code',
    auditEntityKey: 'document_type',
    auditPermission: 'DOCUMENT_TYPE_RECORD_AUDIT_VIEW',
    auditReportPermission: 'DOCUMENT_TYPE_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: /^[A-Z]{1,3}$/, regexMsg: '1 a 3 letras mayúsculas (p.ej. CC, CI)', regexMsgKey: 'catalogs.validation.documentTypeCode', max: 3, placeholder: 'CI' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 60 },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
    ],
  },
  {
    key: 'marital-statuses',
    basePath: '/v1/admin/catalogs/marital-statuses',
    viewPermission: 'MARITAL_STATUS_VIEW_ALL',
    createPermission: 'MARITAL_STATUS_CREATE',
    updatePermission: 'MARITAL_STATUS_UPDATE',
    deletePermission: 'MARITAL_STATUS_DELETE',
    label: 'Estados civiles',
    labelSingular: 'Estado civil',
    labelKey: 'catalogs.registry.marital-statuses.label',
    labelSingularKey: 'catalogs.registry.marital-statuses.labelSingular',
    icon: 'i-lucide-heart-handshake',
    codeField: 'code',
    auditEntityKey: 'marital_status',
    auditPermission: 'MARITAL_STATUS_RECORD_AUDIT_VIEW',
    auditReportPermission: 'MARITAL_STATUS_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: /^[A-Z_]{1,20}$/, regexMsg: codeMsg(20), regexMsgKey: 'catalogs.validation.codeMax', max: 20, placeholder: 'SOLTERO' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 50 },
    ],
  },
  {
    key: 'occupations',
    basePath: '/v1/admin/catalogs/occupations',
    viewPermission: 'OCCUPATION_VIEW_ALL',
    createPermission: 'OCCUPATION_CREATE',
    updatePermission: 'OCCUPATION_UPDATE',
    deletePermission: 'OCCUPATION_DELETE',
    label: 'Ocupaciones',
    labelSingular: 'Ocupación',
    labelKey: 'catalogs.registry.occupations.label',
    labelSingularKey: 'catalogs.registry.occupations.labelSingular',
    icon: 'i-lucide-briefcase',
    auditEntityKey: 'occupation',
    auditPermission: 'OCCUPATION_RECORD_AUDIT_VIEW',
    auditReportPermission: 'OCCUPATION_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
    ],
  },
  {
    key: 'medical-specialties',
    basePath: '/v1/admin/catalogs/medical-specialties',
    viewPermission: 'MEDICAL_SPECIALTY_VIEW_ALL',
    createPermission: 'MEDICAL_SPECIALTY_CREATE',
    updatePermission: 'MEDICAL_SPECIALTY_UPDATE',
    deletePermission: 'MEDICAL_SPECIALTY_DELETE',
    label: 'Especialidades médicas',
    labelSingular: 'Especialidad médica',
    labelKey: 'catalogs.registry.medical-specialties.label',
    labelSingularKey: 'catalogs.registry.medical-specialties.labelSingular',
    icon: 'i-lucide-stethoscope',
    codeField: 'code',
    auditEntityKey: 'medical_specialty',
    auditPermission: 'MEDICAL_SPECIALTY_RECORD_AUDIT_VIEW',
    auditReportPermission: 'MEDICAL_SPECIALTY_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'OFTALMOLOGIA' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
    ],
  },
  {
    key: 'service-categories',
    basePath: '/v1/admin/catalogs/service-categories',
    viewPermission: 'SERVICE_CATEGORY_VIEW_ALL',
    createPermission: 'SERVICE_CATEGORY_CREATE',
    updatePermission: 'SERVICE_CATEGORY_UPDATE',
    deletePermission: 'SERVICE_CATEGORY_DELETE',
    label: 'Categorías de servicio',
    labelSingular: 'Categoría de servicio',
    labelKey: 'catalogs.registry.service-categories.label',
    labelSingularKey: 'catalogs.registry.service-categories.labelSingular',
    icon: 'i-lucide-layers',
    codeField: 'code',
    auditEntityKey: 'service_category',
    auditPermission: 'SERVICE_CATEGORY_RECORD_AUDIT_VIEW',
    auditReportPermission: 'SERVICE_CATEGORY_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'CONSULTA' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
    ],
  },
  {
    key: 'ally-types',
    basePath: '/v1/admin/catalogs/ally-types',
    viewPermission: 'ALLY_TYPE_VIEW_ALL',
    createPermission: 'ALLY_TYPE_CREATE',
    updatePermission: 'ALLY_TYPE_UPDATE',
    deletePermission: 'ALLY_TYPE_DELETE',
    label: 'Tipos de aliado',
    labelSingular: 'Tipo de aliado',
    labelKey: 'catalogs.registry.ally-types.label',
    labelSingularKey: 'catalogs.registry.ally-types.labelSingular',
    icon: 'i-lucide-handshake',
    codeField: 'code',
    auditEntityKey: 'ally_type',
    auditPermission: 'ALLY_RECORD_AUDIT_VIEW',
    auditReportPermission: 'ALLY_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'OPTICA' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
    ],
  },
  {
    key: 'promoter-types',
    basePath: '/v1/admin/catalogs/promoter-types',
    viewPermission: 'PROMOTER_TYPE_VIEW_ALL',
    createPermission: 'PROMOTER_TYPE_CREATE',
    updatePermission: 'PROMOTER_TYPE_UPDATE',
    deletePermission: 'PROMOTER_TYPE_DELETE',
    label: 'Tipos de promotor',
    labelSingular: 'Tipo de promotor',
    labelKey: 'catalogs.registry.promoter-types.label',
    labelSingularKey: 'catalogs.registry.promoter-types.labelSingular',
    icon: 'i-lucide-badge-percent',
    codeField: 'code',
    auditEntityKey: 'promoter_type',
    auditPermission: 'PROMOTER_TYPE_RECORD_AUDIT_VIEW',
    auditReportPermission: 'PROMOTER_TYPE_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'INDEPENDIENTE' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
      // V103 — still-unconfirmed business question (hub notes pregunta 7): default
      // true keeps today's behavior for every existing type.
      { name: 'generatesHierarchyOverride', label: 'Genera override jerárquico', labelKey: 'catalogs.fields.generatesHierarchyOverride', type: 'checkbox', defaultChecked: true },
    ],
  },
  {
    key: 'promoter-ranks',
    basePath: '/v1/admin/promoter-ranks',
    viewPermission: 'PROMOTER_RANK_VIEW_ALL',
    createPermission: 'PROMOTER_RANK_CREATE',
    updatePermission: 'PROMOTER_RANK_UPDATE',
    deletePermission: 'PROMOTER_RANK_DELETE',
    label: 'Cargos jerárquicos',
    labelSingular: 'Cargo jerárquico',
    labelKey: 'catalogs.registry.promoter-ranks.label',
    labelSingularKey: 'catalogs.registry.promoter-ranks.labelSingular',
    icon: 'i-lucide-network',
    codeField: 'code',
    auditEntityKey: 'promoter_rank',
    auditPermission: 'PROMOTER_RANK_RECORD_AUDIT_VIEW',
    auditReportPermission: 'PROMOTER_RANK_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'SUPERVISOR' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 100 },
      // Immutable: the whole hierarchy engine compares by this integer — see
      // hub plan §1. onlyCreate so it can never drift under an existing chain.
      { name: 'hierarchyLevel', label: 'Nivel jerárquico', labelKey: 'catalogs.fields.hierarchyLevel', type: 'number', required: true, onlyCreate: true, min: 1, placeholder: '2' },
      { name: 'maxSubordinates', label: 'Máximo de subordinados', labelKey: 'catalogs.fields.maxSubordinates', type: 'number', min: 1, placeholder: 'Sin límite' },
      // Real parent/superior FK — self-referencing (`parentKey` points at this
      // same catalog). Freely editable (unlike code/hierarchyLevel): reordering
      // within a level goes through the dedicated reorder endpoint, not this
      // field, but re-parenting to a different superior is a plain edit.
      // `null` = top of the hierarchy. Gated by the same `updatePermission`
      // as the rest of the form — no separate field-level permission exists.
      { name: 'parentRankUuid', label: 'Cargo superior', labelKey: 'catalogs.fields.superiorRank', type: 'parent', parentKey: 'promoter-ranks' },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 200 },
    ],
  },
  {
    key: 'currencies',
    basePath: '/v1/admin/currencies',
    viewPermission: 'CURRENCY_VIEW_ALL',
    createPermission: 'CURRENCY_CREATE',
    updatePermission: 'CURRENCY_UPDATE',
    deletePermission: 'CURRENCY_DELETE',
    label: 'Monedas',
    labelSingular: 'Moneda',
    labelKey: 'catalogs.registry.currencies.label',
    labelSingularKey: 'catalogs.registry.currencies.labelSingular',
    icon: 'i-lucide-coins',
    codeField: 'code',
    auditEntityKey: 'currency',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: /^[A-Z]{3,4}$/, regexMsg: 'Tres o cuatro letras mayúsculas (ISO 4217, p.ej. USD)', regexMsgKey: 'catalogs.validation.currencyCode', max: 4, placeholder: 'USD' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 60 },
      { name: 'symbol', label: 'Símbolo', labelKey: 'catalogs.fields.symbol', type: 'text', required: true, max: 6, placeholder: '$' },
      { name: 'decimalPlaces', label: 'Decimales', labelKey: 'catalogs.fields.decimalPlaces', type: 'number', required: true, min: 0, placeholder: '2' },
    ],
  },
  {
    // Bank master catalog (V116, hub plan payments-unification) — prerequisite
    // of payment_lines.bank_id for any method that requires a bank account.
    key: 'banks',
    basePath: '/v1/admin/banks',
    viewPermission: 'BANK_VIEW_ALL',
    createPermission: 'BANK_CREATE',
    updatePermission: 'BANK_UPDATE',
    deletePermission: 'BANK_DELETE',
    label: 'Bancos',
    labelSingular: 'Banco',
    labelKey: 'catalogs.registry.banks.label',
    labelSingularKey: 'catalogs.registry.banks.labelSingular',
    icon: 'i-lucide-landmark',
    codeField: 'code',
    auditEntityKey: 'bank',
    auditPermission: 'BANK_RECORD_AUDIT_VIEW',
    auditReportPermission: 'BANK_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: /^[0-9]{1,10}$/, regexMsg: 'Código SUDEBAN numérico, máx. 10 dígitos', regexMsgKey: 'catalogs.validation.codeMax', max: 10, placeholder: '0102' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 120, placeholder: 'Banco de Venezuela S.A.C.A. Banco Universal' },
      { name: 'shortName', label: 'Nombre comercial', labelKey: 'catalogs.fields.shortName', type: 'text', required: true, max: 60, placeholder: 'Banco de Venezuela' },
      { name: 'taxDocumentType', label: 'Tipo de RIF', labelKey: 'catalogs.fields.taxDocumentType', type: 'text', required: true, regex: /^[JVEGP]$/, regexMsg: 'Una letra: J, G, V, E o P', regexMsgKey: 'catalogs.validation.taxDocumentType', max: 1, placeholder: 'J' },
      { name: 'taxDocumentNumber', label: 'Número de RIF', labelKey: 'catalogs.fields.taxDocumentNumber', type: 'text', required: true, max: 20, placeholder: '070133805' },
    ],
  },
  {
    // Payment reason/category catalog (V115) — payments.payment_type_id.
    // Not the same catalog as payment-methods (line-level, below).
    key: 'payment-categories',
    basePath: '/v1/admin/payment-categories',
    viewPermission: 'PAYMENT_CATEGORY_VIEW_ALL',
    createPermission: 'PAYMENT_CATEGORY_CREATE',
    updatePermission: 'PAYMENT_CATEGORY_UPDATE',
    deletePermission: 'PAYMENT_CATEGORY_DELETE',
    label: 'Categorías de pago',
    labelSingular: 'Categoría de pago',
    labelKey: 'catalogs.registry.payment-categories.label',
    labelSingularKey: 'catalogs.registry.payment-categories.labelSingular',
    icon: 'i-lucide-tags',
    codeField: 'code',
    auditEntityKey: 'payment_category',
    auditPermission: 'PAYMENT_CATEGORY_RECORD_AUDIT_VIEW',
    auditReportPermission: 'PAYMENT_CATEGORY_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'MEMBERSHIP_FEE' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 80 },
      { name: 'direction', label: 'Dirección', labelKey: 'catalogs.fields.direction', type: 'text', required: true, regex: /^(IN|OUT)$/, regexMsg: 'Debe ser IN u OUT', regexMsgKey: 'catalogs.validation.direction', max: 3, placeholder: 'IN' },
      { name: 'description', label: 'Descripción', labelKey: 'catalogs.fields.description', type: 'textarea', max: 255 },
    ],
  },
  {
    // Payment method catalog (V115) — payment_lines.payment_type_id (the
    // line-level HOW, not the header-level WHY above).
    key: 'payment-methods',
    basePath: '/v1/admin/payment-methods',
    viewPermission: 'PAYMENT_METHOD_VIEW_ALL',
    createPermission: 'PAYMENT_METHOD_CREATE',
    updatePermission: 'PAYMENT_METHOD_UPDATE',
    deletePermission: 'PAYMENT_METHOD_DELETE',
    label: 'Métodos de pago',
    labelSingular: 'Método de pago',
    labelKey: 'catalogs.registry.payment-methods.label',
    labelSingularKey: 'catalogs.registry.payment-methods.labelSingular',
    icon: 'i-lucide-credit-card',
    codeField: 'code',
    auditEntityKey: 'payment_method',
    auditPermission: 'PAYMENT_METHOD_RECORD_AUDIT_VIEW',
    auditReportPermission: 'PAYMENT_METHOD_REPORT_AUDIT_VIEW',
    fields: [
      { name: 'code', label: 'Código', labelKey: 'catalogs.fields.code', type: 'text', required: true, onlyCreate: true, regex: CODE_40, regexMsg: codeMsg(40), regexMsgKey: 'catalogs.validation.codeMax', max: 40, placeholder: 'BANK_TRANSFER' },
      { name: 'name', label: 'Nombre', labelKey: 'catalogs.fields.name', type: 'text', required: true, max: 80 },
      { name: 'mandatoryBankAccount', label: 'Exige cuenta bancaria', labelKey: 'catalogs.fields.mandatoryBankAccount', type: 'checkbox' },
      { name: 'mandatoryPhone', label: 'Exige teléfono', labelKey: 'catalogs.fields.mandatoryPhone', type: 'checkbox' },
      { name: 'mandatoryEmail', label: 'Exige correo', labelKey: 'catalogs.fields.mandatoryEmail', type: 'checkbox' },
      { name: 'mandatoryReferenceNumber', label: 'Exige número de referencia', labelKey: 'catalogs.fields.mandatoryReferenceNumber', type: 'checkbox' },
    ],
  },
]

/** Finds a catalog definition by its route key. */
export function getCatalogDef(key: string): CatalogDef | undefined {
  return CATALOGS.find(c => c.key === key)
}
