// Catálogo de permisos sembrados en el backend (V6__seed_roles.sql y migraciones posteriores).
// Ver "Flujo de seguridad y permisos" → Matriz de roles × permisos.
// Úsalos como fuente de autocompletado/tipado en can(), v-can y definePageMeta.

export const PERMISSIONS = [
  // USERS
  'USER_CREATE',
  // Also covers assigning/revoking a user's roles — the PUT carries the roleIds.
  'USER_UPDATE',
  'USER_DELETE',
  'USER_VIEW_ALL',
  'USER_RESET_PASSWORD',
  // Role management — one key per action (V32).
  'ROLE_VIEW',
  'ROLE_CREATE',
  'ROLE_UPDATE',
  'ROLE_DELETE',
  // Assigning permissions to a role only (PUT /v1/admin/roles/{uuid}/permissions).
  'ROLE_PERMISSION_EDIT',
  // Users assigned to a role (V79) — GET uses ROLE_USER_VIEW_ALL, POST/DELETE use CREATE/DELETE.
  'ROLE_USER_VIEW_ALL',
  'ROLE_USER_CREATE',
  'ROLE_USER_DELETE',

  // CATALOGS
  // 4 granular permissions per catalog (V78): view/create/update/delete, so a
  // role can have read-only access to one catalog and full CRUD on another.
  'COUNTRY_VIEW_ALL', 'COUNTRY_CREATE', 'COUNTRY_UPDATE', 'COUNTRY_DELETE',
  'STATE_VIEW_ALL', 'STATE_CREATE', 'STATE_UPDATE', 'STATE_DELETE',
  'CITY_VIEW_ALL', 'CITY_CREATE', 'CITY_UPDATE', 'CITY_DELETE',
  'GENDER_VIEW_ALL', 'GENDER_CREATE', 'GENDER_UPDATE', 'GENDER_DELETE',
  'DOCUMENT_TYPE_VIEW_ALL', 'DOCUMENT_TYPE_CREATE', 'DOCUMENT_TYPE_UPDATE', 'DOCUMENT_TYPE_DELETE',
  'MARITAL_STATUS_VIEW_ALL', 'MARITAL_STATUS_CREATE', 'MARITAL_STATUS_UPDATE', 'MARITAL_STATUS_DELETE',
  'OCCUPATION_VIEW_ALL', 'OCCUPATION_CREATE', 'OCCUPATION_UPDATE', 'OCCUPATION_DELETE',
  'MEDICAL_SPECIALTY_VIEW_ALL', 'MEDICAL_SPECIALTY_CREATE', 'MEDICAL_SPECIALTY_UPDATE', 'MEDICAL_SPECIALTY_DELETE',
  'SERVICE_CATEGORY_VIEW_ALL', 'SERVICE_CATEGORY_CREATE', 'SERVICE_CATEGORY_UPDATE', 'SERVICE_CATEGORY_DELETE',
  'ALLY_TYPE_VIEW_ALL', 'ALLY_TYPE_CREATE', 'ALLY_TYPE_UPDATE', 'ALLY_TYPE_DELETE',
  'PROMOTER_TYPE_VIEW_ALL', 'PROMOTER_TYPE_CREATE', 'PROMOTER_TYPE_UPDATE', 'PROMOTER_TYPE_DELETE',

  // MEMBERS
  'MEMBER_CREATE',
  'MEMBER_UPDATE',
  'MEMBER_DELETE',
  'MEMBER_VIEW_ALL',
  'MEMBER_VIEW_OWN',
  'MEMBER_UPLOAD_DOCUMENT',
  'MEDICAL_RECORD_VIEW',
  'MEDICAL_RECORD_UPDATE',
  // Corporate contracts (V38, granular per V79). Member enrollment is a
  // separate association concern with its own CRUD set.
  'CORPORATE_CONTRACT_VIEW_ALL',
  'CORPORATE_CONTRACT_CREATE',
  'CORPORATE_CONTRACT_UPDATE',
  'CORPORATE_CONTRACT_DELETE',
  'CORPORATE_CONTRACT_MEMBER_VIEW_ALL',
  'CORPORATE_CONTRACT_MEMBER_CREATE',
  'CORPORATE_CONTRACT_MEMBER_UPDATE',
  'CORPORATE_CONTRACT_MEMBER_DELETE',

  // SUBSIDIES
  'SUBSIDY_VIEW_ALL',
  'SUBSIDY_VIEW_OWN',
  'SUBSIDY_CREATE',
  'SUBSIDY_UPDATE',
  'SUBSIDY_DELETE',

  // ALLIES
  'ALLY_CREATE',
  'ALLY_UPDATE',
  'ALLY_DELETE',
  'ALLY_VIEW_ALL',
  'ALLY_VIEW_OWN',
  // Contracts with the ally (V79) — even reads stay off ALLY_VIEW_ALL, since
  // agreements include commercial terms not every ally-viewer role should see.
  'ALLY_AGREEMENT_VIEW_ALL',
  'ALLY_AGREEMENT_CREATE',
  'ALLY_AGREEMENT_UPDATE',
  'ALLY_AGREEMENT_DELETE',
  // Staff assigned to operate on an ally's behalf (V79), decoupled from ALLY_VIEW_ALL/UPDATE.
  'ALLY_USER_VIEW_ALL',
  'ALLY_USER_CREATE',
  'ALLY_USER_UPDATE',
  'ALLY_USER_DELETE',
  'ALLY_VALIDATE_MEMBER',
  'ALLY_REGISTER_USAGE',

  // PLANS
  'PLAN_CREATE',
  'PLAN_UPDATE',
  'PLAN_DELETE',
  'PLAN_VIEW_ALL',

  // MEMBERSHIPS
  'MEMBERSHIP_CREATE',
  'MEMBERSHIP_UPDATE',
  'MEMBERSHIP_CANCEL',
  'MEMBERSHIP_REACTIVATE',
  'MEMBERSHIP_VIEW_ALL',
  'MEMBERSHIP_VIEW_OWN',

  // PAYMENTS
  'PAYMENT_CREATE',
  'PAYMENT_APPROVE',
  'PAYMENT_REJECT',
  'PAYMENT_VIEW_ALL',
  'PAYMENT_VIEW_OWN',

  // PROMOTERS
  'PROMOTER_CREATE',
  'PROMOTER_UPDATE',
  'PROMOTER_DELETE',
  'PROMOTER_VIEW_ALL',
  // Hierarchy (V101/V104, hub plan) — cargo catalog, supervisor reassignment, rank changes.
  'PROMOTER_RANK_VIEW_ALL', 'PROMOTER_RANK_CREATE', 'PROMOTER_RANK_UPDATE', 'PROMOTER_RANK_DELETE',
  'PROMOTER_ASSIGN_SUPERVISOR',
  'PROMOTER_CHANGE_RANK',
  // Hierarchy-override bands (V102/V108, hub plan §2) — Supervisor/Coordinador override %.
  'HIERARCHY_OVERRIDE_TIER_VIEW_ALL', 'HIERARCHY_OVERRIDE_TIER_CREATE', 'HIERARCHY_OVERRIDE_TIER_UPDATE', 'HIERARCHY_OVERRIDE_TIER_DELETE',

  // COMMISSIONS
  'COMMISSION_VIEW_ALL',
  'COMMISSION_VIEW_OWN',
  'COMMISSION_PAYOUT',
  'COMMISSION_RE_RATE',
  'COMMISSION_VOID',
  // Granular per V79: view/create/update/delete instead of one bundled _MANAGE.
  'COMMISSION_TIER_VIEW_ALL', 'COMMISSION_TIER_CREATE', 'COMMISSION_TIER_UPDATE', 'COMMISSION_TIER_DELETE',
  'BONUS_RULE_VIEW_ALL', 'BONUS_RULE_CREATE', 'BONUS_RULE_UPDATE', 'BONUS_RULE_DELETE',
  'COLLECTION_COMMISSION_TIER_VIEW_ALL', 'COLLECTION_COMMISSION_TIER_CREATE', 'COLLECTION_COMMISSION_TIER_UPDATE', 'COLLECTION_COMMISSION_TIER_DELETE',
  'LEADERBOARD_PRIZE_VIEW_ALL', 'LEADERBOARD_PRIZE_CREATE', 'LEADERBOARD_PRIZE_UPDATE', 'LEADERBOARD_PRIZE_DELETE',
  // Mark-as-paid workflow (V92) — separate from creation/awarding.
  'BONUS_AWARD_PAY',
  'LEADERBOARD_PRIZE_PAY',

  // REFERRALS
  'REFERRAL_CODE_CREATE',
  'REFERRAL_CODE_VIEW_ALL',
  'REFERRAL_CODE_VIEW_OWN',

  // SCHEDULED JOBS
  'JOB_VIEW_ALL',
  'JOB_CREATE',
  'JOB_UPDATE',
  'JOB_DELETE',
  'JOB_RUN_NOW',

  // REPORTS
  'REPORT_VIEW_DASHBOARD',
  'REPORT_EXPORT',
  'ALLY_REPORT_GENERATE',
  'MEMBER_REPORT_GENERATE',
  'USER_REPORT_GENERATE',
  'PLAN_REPORT_GENERATE',
  'MEMBERSHIP_REPORT_GENERATE',
  'PAYMENT_REPORT_GENERATE',
  'PROMOTER_REPORT_GENERATE',
  'COMMISSION_REPORT_GENERATE',
  'REFERRAL_REPORT_GENERATE',
  'JOB_REPORT_GENERATE',
  'REPORT_REPORT_GENERATE',
  'REPORT_SHARE',

  // AUDIT
  'AUDIT_VIEW_ALL',
  'AUDIT_VIEW_LOGIN',
  'REPORT_AUDIT_VIEW_ALL',
  'USER_RECORD_AUDIT_VIEW',
  'MEMBER_RECORD_AUDIT_VIEW',
  'ALLY_RECORD_AUDIT_VIEW',
  'PLAN_RECORD_AUDIT_VIEW',
  'MEMBERSHIP_RECORD_AUDIT_VIEW',
  'PAYMENT_RECORD_AUDIT_VIEW',
  'PROMOTER_RECORD_AUDIT_VIEW',
  'COMMISSION_RECORD_AUDIT_VIEW',
  'REFERRAL_RECORD_AUDIT_VIEW',
  'USER_REPORT_AUDIT_VIEW',
  'MEMBER_REPORT_AUDIT_VIEW',
  'ALLY_REPORT_AUDIT_VIEW',
  'PLAN_REPORT_AUDIT_VIEW',
  'MEMBERSHIP_REPORT_AUDIT_VIEW',
  'PAYMENT_REPORT_AUDIT_VIEW',
  'PROMOTER_REPORT_AUDIT_VIEW',
  'COMMISSION_REPORT_AUDIT_VIEW',
  'REFERRAL_REPORT_AUDIT_VIEW',

  // CURRENCY (ADR 0015 — multi-currency) — V92/V96/V98
  'CURRENCY_VIEW_ALL', 'CURRENCY_CREATE', 'CURRENCY_UPDATE', 'CURRENCY_DELETE',
  // EXCHANGE_RATE_VIEW_ALL/CREATE (V92) + UPDATE/DELETE (V96, MANUAL rows only).
  'EXCHANGE_RATE_VIEW_ALL', 'EXCHANGE_RATE_CREATE', 'EXCHANGE_RATE_UPDATE', 'EXCHANGE_RATE_DELETE',
  // ORGANIZATION (V98) — single-row read/update, no create/delete.
  'ORGANIZATION_VIEW',
  'ORGANIZATION_UPDATE',

  // ENTITY_CONFIG (V81) — SYSTEM-only for now
  'ENTITY_CONFIG_VIEW',
  'ENTITY_CONFIG_CREATE',
  'ENTITY_CONFIG_UPDATE',
  'ENTITY_CONFIG_DELETE',
] as const

export type Permission = (typeof PERMISSIONS)[number]
